name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Change to your branch if needed.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check requirements.txt
        run: cat requirements.txt || echo "Flask==2.2.2" > requirements.txt

      - name: Create Dockerfile
        run: |
          echo "FROM python:3.9-slim" > Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY . /app" >> Dockerfile
          echo "RUN pip install --upgrade pip" >> Dockerfile
          echo "RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi" >> Dockerfile
          echo 'CMD ["python", "app.py"]' >> Dockerfile
          cat Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: pratikp02/flaskapp:latest

      - name: Logout from Docker Hub
        run: docker logout

      - name: Install SSH Client and sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
            docker pull pratikp02/flaskapp:latest
            docker stop flaskapp || true
            docker rm flaskapp || true
            docker run -d --name flaskapp -p 80:5000 pratikp02/flaskapp:latest
          EOF
