name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Change to your branch if needed.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Dockerfile
        run: |
          echo "FROM python:3.9-slim" > Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY . /app" >> Dockerfile
          echo "RUN pip install --no-cache-dir -r requirements.txt" >> Dockerfile
          echo 'CMD ["python", "app.py"]' >> Dockerfile
          cat Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: pratikp02/flaskapp:latest

      - name: Logout from Docker Hub
        run: docker logout

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull pratikp02/flaskapp:latest
            docker stop flaskapp || true
            docker rm flaskapp || true
            docker run -d --name flaskapp -p 80:5000 sreehariskumar/flaskapp:latest
